# SPDX-FileCopyrightText: 2022 Harish Rajagopal <harish.rajagopals@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[background]
# Path to the background image
#path = "$(echo /home/*/wallpapers/)$(ls -1 /home/*/wallpapers | shuf | head -1)"
path = "/etc/greetd/lantern-light-room.png"
# How the background image covers the screen if the aspect ratio doesn't match
# Available values: "Fill", "Contain", "Cover", "ScaleDown"
# Refer to: https://docs.gtk.org/gtk4/enum.ContentFit.html
# NOTE: This is ignored if ReGreet isn't compiled with GTK v4.8 support.
fit = "Cover"

# The entries defined in this section will be passed to the session as environment variables when it is started
#[env]
#ENV_VARIABLE = "value"

[GTK]
# Whether to use the dark theme
application_prefer_dark_theme = true

# Cursor theme name
cursor_theme_name = "rose-pine-hyprcursor"

# Icon theme name
icon_theme_name = "Papirus-Dark"

# GTK theme name
theme_name = "Catpuccin-Dark"

# Font name and size
font_name = "JetBrainsMono 16"

[commands]
# The command used to reboot the system
reboot = ["systemctl", "reboot"]

# The command used to shut down the system
poweroff = ["systemctl", "poweroff"]

# The command prefix for X11 sessions to start the X server
x11_prefix = [ "startx", "/usr/bin/env" ]

[appearance]
# The message that initially displays on startup
greeting_msg = "Welcome back!"


[widget.clock]
# strftime format argument
# See https://docs.rs/jiff/0.1.14/jiff/fmt/strtime/index.html#conversion-specifications
format = "%a %H:%M"

# How often to update the text
resolution = "500ms"

# Ask GTK to make the label at least this wide. This helps keeps the parent element layout and width consistent.
# Experiment with different widths, the interpretation of this value is entirely up to GTK.
label_width = 150
